SELECT
    PK.TBCREATOR AS PK_SCHEMA,
    PK.TBNAME AS PK_TABLE,
    PK.COLNAME AS PK_COLUMN,
    FK.REFTBCREATOR AS FK_SCHEMA,
    FK.REFTBNAME AS FK_TABLE,
    FK.REFCOLNAME AS FK_COLUMN
FROM
    SYSIBM.SYSFOREIGNKEYS FK
    JOIN SYSIBM.SYSKEYS PK
        ON FK.TBCREATOR = PK.TBCREATOR
        AND FK.TBNAME = PK.TBNAME
        AND FK.UNIQUE_COLNAME = PK.COLNAME
